# Generated by Django 5.2.1 on 2025-08-12 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_rename_psot_comment_post_post_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
